#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v20
# autospec commit: f35655a
#
Name     : R-cards
Version  : 0.2.2
Release  : 2
URL      : https://cran.r-project.org/src/contrib/cards_0.2.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/cards_0.2.2.tar.gz
Summary  : Analysis Results Data
Group    : Development/Tools
License  : Apache-2.0
Requires: R-cli
Requires: R-dplyr
Requires: R-glue
Requires: R-rlang
Requires: R-tidyr
Requires: R-tidyselect
BuildRequires : R-cli
BuildRequires : R-dplyr
BuildRequires : R-glue
BuildRequires : R-rlang
BuildRequires : R-tidyr
BuildRequires : R-tidyselect
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Consortium) compliant Analysis Results Data objects. These objects are
    used and re-used to construct summary tables, visualizations, and
    written reports. The package also exports utilities for working with
    these objects and creating new Analysis Results Data objects.

%prep
%setup -q -n cards

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726855955

%install
export SOURCE_DATE_EPOCH=1726855955
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/cards/DESCRIPTION
/usr/lib64/R/library/cards/INDEX
/usr/lib64/R/library/cards/Meta/Rd.rds
/usr/lib64/R/library/cards/Meta/data.rds
/usr/lib64/R/library/cards/Meta/features.rds
/usr/lib64/R/library/cards/Meta/hsearch.rds
/usr/lib64/R/library/cards/Meta/links.rds
/usr/lib64/R/library/cards/Meta/nsInfo.rds
/usr/lib64/R/library/cards/Meta/package.rds
/usr/lib64/R/library/cards/NAMESPACE
/usr/lib64/R/library/cards/NEWS.md
/usr/lib64/R/library/cards/R/cards
/usr/lib64/R/library/cards/R/cards.rdb
/usr/lib64/R/library/cards/R/cards.rdx
/usr/lib64/R/library/cards/WORDLIST
/usr/lib64/R/library/cards/data/Rdata.rdb
/usr/lib64/R/library/cards/data/Rdata.rds
/usr/lib64/R/library/cards/data/Rdata.rdx
/usr/lib64/R/library/cards/help/AnIndex
/usr/lib64/R/library/cards/help/aliases.rds
/usr/lib64/R/library/cards/help/cards.rdb
/usr/lib64/R/library/cards/help/cards.rdx
/usr/lib64/R/library/cards/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/cards/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/cards/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/cards/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/cards/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/cards/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/cards/help/figures/lifecycle-soft-deprecated.svg
/usr/lib64/R/library/cards/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/cards/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/cards/help/figures/logo.png
/usr/lib64/R/library/cards/help/paths.rds
/usr/lib64/R/library/cards/html/00Index.html
/usr/lib64/R/library/cards/html/R.css
/usr/lib64/R/library/cards/tests/spelling.R
/usr/lib64/R/library/cards/tests/testthat.R
/usr/lib64/R/library/cards/tests/testthat/_snaps/add_calculated_row.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/apply_fmt_fn.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/ard_attributes.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/ard_categorical.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/ard_complex.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/ard_continuous.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/ard_dichotomous.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/ard_hierarchical.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/ard_missing.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/ard_stack.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/ard_total_n.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/as_card.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/as_nested_list.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/bind_ard.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/check_ard_structure.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/check_pkg_installed.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/eval_capture_conditions.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/get_ard_statistics.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/print.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/print_ard_conditions.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/process_selectors.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/round5.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/shift_ard_columns.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/shuffle_ard.md
/usr/lib64/R/library/cards/tests/testthat/_snaps/tidy_as_ard.md
/usr/lib64/R/library/cards/tests/testthat/test-add_calculated_row.R
/usr/lib64/R/library/cards/tests/testthat/test-apply_fmt_fn.R
/usr/lib64/R/library/cards/tests/testthat/test-ard_attributes.R
/usr/lib64/R/library/cards/tests/testthat/test-ard_categorical.R
/usr/lib64/R/library/cards/tests/testthat/test-ard_complex.R
/usr/lib64/R/library/cards/tests/testthat/test-ard_continuous.R
/usr/lib64/R/library/cards/tests/testthat/test-ard_dichotomous.R
/usr/lib64/R/library/cards/tests/testthat/test-ard_hierarchical.R
/usr/lib64/R/library/cards/tests/testthat/test-ard_missing.R
/usr/lib64/R/library/cards/tests/testthat/test-ard_stack.R
/usr/lib64/R/library/cards/tests/testthat/test-ard_total_n.R
/usr/lib64/R/library/cards/tests/testthat/test-as_card.R
/usr/lib64/R/library/cards/tests/testthat/test-as_nested_list.R
/usr/lib64/R/library/cards/tests/testthat/test-bind_ard.R
/usr/lib64/R/library/cards/tests/testthat/test-check_ard_structure.R
/usr/lib64/R/library/cards/tests/testthat/test-check_pkg_installed.R
/usr/lib64/R/library/cards/tests/testthat/test-eval_capture_conditions.R
/usr/lib64/R/library/cards/tests/testthat/test-get_ard_statistics.R
/usr/lib64/R/library/cards/tests/testthat/test-label_cards.R
/usr/lib64/R/library/cards/tests/testthat/test-nest_for_ard.R
/usr/lib64/R/library/cards/tests/testthat/test-print.R
/usr/lib64/R/library/cards/tests/testthat/test-print_ard_conditions.R
/usr/lib64/R/library/cards/tests/testthat/test-process_selectors.R
/usr/lib64/R/library/cards/tests/testthat/test-replace_null_statistic.R
/usr/lib64/R/library/cards/tests/testthat/test-round5.R
/usr/lib64/R/library/cards/tests/testthat/test-selectors.R
/usr/lib64/R/library/cards/tests/testthat/test-shift_ard_columns.R
/usr/lib64/R/library/cards/tests/testthat/test-shuffle_ard.R
/usr/lib64/R/library/cards/tests/testthat/test-tidy_as_ard.R
